--1
CREATE TABLE EMPLOYEES (
   EMPID INT,
   NAME VARCHAR(50),
   SALARY DECIMAL(10,2)
);
--2
INSERT INTO EMPLOYEES(EMPID, NAME, SALARY)
VALUES
    (1,'JOHN BLACK', 7000.55),
	(2,'ENOLA HOLMES', 8000.75),
	(3,'JANE SMITH', 5000.15);
SELECT * FROM EMPLOYEES;
--3
UPDATE EMPLOYEES
SET SALARY=7500.55
WHERE EMPID=1;
SELECT * FROM EMPLOYEES;
--4
DELETE FROM EMPLOYEES
WHERE EMPID=2;
SELECT * FROM EMPLOYEES;
--5
CREATE TABLE TESTtable (
      ID INT,
	  DATA VARCHAR(20)
);
SELECT * FROM TESTtable;
INSERT INTO TESTtable(ID,DATA)
VALUES
     (1,'RECORDING 1'),
	 (2,'RECORDING 2'),
	 (3,'RECORDING 3');
SELECT * FROM TESTtable;
DELETE FROM TESTtable
WHERE ID=3;
SELECT * FROM TESTtable;
TRUNCATE TABLE TESTtable;
DROP TABLE TESTtable;
--6
ALTER TABLE EMPLOYEES
ALTER COLUMN NAME VARCHAR(100);
SELECT * FROM EMPLOYEES;
--7
ALTER TABLE EMPLOYEES
ADD Department VARCHAR(50);
SELECT * FROM EMPLOYEES;
--8
ALTER TABLE EMPLOYEES
ALTER COLUMN SALARY FLOAT;
SELECT * FROM EMPLOYEES;
--9
DROP TABLE DEPARTMENTS;
GO
CREATE TABLE Departments (
   DEPARTMENTID INT PRIMARY KEY,
   DEPARTMENTNAME VARCHAR(50)
);
SELECT * FROM EMPLOYEES;
--10
TRUNCATE TABLE EMPLOYEES;
SELECT * FROM EMPLOYEES;
--11
INSERT INTO Departments(DEPARTMENTNAME)
VALUES
   (100,'MARKETING'),
   (101,'RESEARCH'),
   (102,'IT'),
   (103,'SALES');
SELECT * FROM EMPLOYEES;
CREATE TABLE TEMPDEPARTMENTS (
    TEMPDEPTID INT,
	TEMPDEPTNAME VARCHAR(50)
);
INSERT INTO TEMPDEPARTMENTS(TEMPDEPTID, TEMPDEPTNAME)
VALUES
  (200,'LEGAL'),
  (201,'CUSTOMER SERVICE'),
  (202,'LEARNING'),
  (203,'TECHNOLOGY'),
  (204,'OPERATIONS');
INSERT INTO DEPARTMENTS(DEPARTMENTID, DEPARTMENTNAME)
SELECT TEMPDEPTID, TEMPDEPTNAME FROM TEMPDEPARTMENTS;

SELECT * FROM DEPARTMENTS;
DROP TABLE TEMPDEPARTMENTS;
--12
UPDATE EMPLOYEES
SET DEPARTMENT='MANAGEMENT'
WHERE SALARY > 5000;
SELECT * FROM EMPLOYEES;
--13
TRUNCATE TABLE EMPLOYEES;
--14
ALTER TABLE EMPLOYEES
DROP COLUMN DEPARTMENT;
SELECT * FROM EMPLOYEES;
--15
EXEC sp_rename 'EMPLOYEES', 
'STAFFMEMBER';
SELECT * FROM STAFFMEMBER;
--16
DROP TABLE DEPARTMENTS;
--17
CREATE TABLE PRODUCTS (
    PRODUCTID INT PRIMARY KEY,
	PRODUCTNAME VARCHAR(255),
	CATEGORY VARCHAR(100),
	PRICE DECIMAL(10,2),
	STOCKQUANTITY INT
);
SELECT * FROM PRODUCTS
--18
ALTER TABLE PRODUCTS
ADD CONSTRAINT CK_PRODUCTPRICE CHECK(PRICE > 0);
--19
ALTER TABLE PRODUCTS
ALTER COLUMN STOCKQUANTITY INT DEFAULT 50;
--20
EXEC sp_rename 'PRODUCTS.CATEGORY','PRODUCTCATEGORY','COLUMN';
--21
INSERT INTO PRODUCTS(PRODUCTID, PRODUCTNAME,PRODUCTCATEGORY,PRICE,STOCKQUANTITY)
VALUES
      (1,'LAPTOP','ELECTRONICS',3000.85,100),
	  (2,'DRESS','OTHER',450.85,15),
	  (3,'COFFEE','BEVERAGES',850.45,450),
	  (4,'COFFEE MAKER','APPLIANCES',2000.35,2),
	  (5,'BOOK','BOOKS',50.25,400);
--22
SELECT * INTO PRODUCTSBACKUP FROM PRODUCTS;
--23
EXEC sp_rename 'PRODUCTSBACKUP', 'INVENTORY';
--24
ALTER TABLE INVENTORY 
ALTER COLUMN PRICE FLOAT;
--26
ALTER TABLE INVENTORY
ADD PRODUCTCODE INT IDENTITY(1000,5);


   






