--1
SELECT PRODUCTNAME AS NAME FROM PRODUCTS;
--2
SELECT * FROM CUSTOMERS AS CLIENT;
--3
SELECT PRODUCTNAME FROM PRODUCTS
UNION 
SELECT PRODUCTNAME FROM PRODUCTS_DISCOUNTED;
--4
SELECT DISTINCT FIRSTNAME,
COUNTRY FROM CUSTOMERS;
--5
SELECT PRODUCTNAME,PRICE, CASE 
WHEN PRICE > 1000 THEN 'HIGH'
WHEN PRICE < 1000 THEN 'LOW'
ELSE 'EQUAL TO 1000' 
END AS PRICECATEGORY FROM PRODUCTS;
--7
SELECT PRODUCTNAME, STOCKQUANTITY,
IIF(STOCKQUANTITY > 100, 'YES', 'NO') AS ISHIGHSTOCK FROM PRODUCTS_DISCOUNTED;
--8
SELECT PRODUCTNAME FROM PRODUCTS
UNION
SELECT PRODUCTNAME FROM OUTOFSTOCK;
--9
SELECT PRODUCTNAME FROM PRODUCTS
EXCEPT
SELECT PRODUCTNAME FROM PRODUCTS_DISCOUNTED;
--10
SELECT PRODUCTNAME, PRICE,
IIF(PRICE > 1000, 'EXPENSIVE', 'AFFORDABLE') AS PRICECATEGORY FROM PRODUCTS;
--11
SELECT FIRSTNAME, LASTNAME, AGE, SALARY FROM EMPLOYEES WHERE AGE < 25 OR SALARY > 60000;
--12
UPDATE EMPLOYEES 
SET SALARY = CASE WHEN DEPARTMENT = 'HR' THEN SALARY * 1.10 OR EMPLOYEEID=5
END;
--13
SELECT PRODUCTNAME FROM PRODUCTS
INTERSECT
SELECT PRODUCTNAME FROM PRODUCTS_DISCOUNTED;
--14
SELECT 
s.SALEID,
p.PRODUCTNAME,
s.Saleamount * p.PRICE AS SALEAMOUNT,
CASE WHEN s.Saleamount * p.PRICE > 500 THEN 'TOP TIER'
     WHEN s.Saleamount * p.PRICE BETWEEN 200 AND 500 THEN 'MID TIER'
	 ELSE 'LOW TIER'
	 END AS SALESTIER 
FROM SALES s
JOIN PRODUCTS p ON S.PRODUCTID = p.PRODUCTID;
--15
SELECT CUSTOMERID FROM ORDERS
EXCEPT
SELECT CUSTOMERID FROM INVOICES;
--16
SELECT
CUSTOMERID,
QUANTITY,
CASE 
WHEN QUANTITY = 1 THEN 3
WHEN QUANTITY > 1 AND QUANTITY < 3 THEN 5
ELSE 7
END AS DISCOUNTPERCENTAGE FROM ORDERS;











